version: '3.4'

services:
  senderapi:
    image: ${DOCKER_REGISTRY-}senderapi
    build:
      context: .
      dockerfile: SenderApi/Dockerfile

  receiver1api:
    image: ${DOCKER_REGISTRY-}receiver1api
    build:
      context: .
      dockerfile: Receiver1Api/Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
